---
- name: httpd-service-reload
  systemd:
    name: "{{ apache_package_name }}.service"
    state: reloaded
    enabled: yes
    no_block: yes

- name: wait-for-httpd
  wait_for:
    port: 443
    delay: 5
